version: '3.8'
services:
  prometheus:
    image: prom/prometheus:v2.29.1
    container_name: prometheus
    volumes:
      - ./config/prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
#    ports:
#      - 9090:9090
    links:
      - alertmanager:alertmanager
    networks:
      - prom-stack
    restart: always

  blackbox:
    image: prom/blackbox-exporter
    container_name: blackbox
    command:
      - '--config.file=/config/blackbox.yml'
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    ports:
      - 9115:9115
    volumes:
      - ./config/blackbox/:/config
    networks:
      - prom-stack
    
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./config/alertmanager/:/etc/alertmanager/
    networks:
      - prom-stack
    restart: always
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - "--web.external-url=https://alert.company.ru:8080"

  grafana:
    image: grafana/grafana:8.1.2
    container_name: grafana
    hostname: grafana.company.ru
    user: "472"
    restart: always
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/:/etc/grafana/
    env_file:
      - ./config/grafana/config.monitoring
    networks:
      - prom-stack

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./config/nginx/ssl.conf:/etc/nginx/ssl.conf
      - /etc/ssl/rv-ssl:/etc/ssl/rv-ssl
    depends_on:
      - prometheus
      - grafana
      - blackbox
      - alertmanager
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 8090:8090 # port for alertmanager
    networks:
      - prom-stack

  gitlab-ci-pipelines-exporter:
    image: docker.io/mvisonneau/gitlab-ci-pipelines-exporter:v0.5.2
    container_name: gitlab-ci-exporter
    ports:
      - 8081:8080
    environment:
      GCPE_CONFIG: /etc/gitlab-ci-pipelines-exporter.yml
      GCPE_INTERNAL_MONITORING_LISTENER_ADDRESS: tcp://127.0.0.1:8082
    volumes:
      - type: bind
        source: ./config/gitlab-ci-exporter/gitlab-ci-pipelines-exporter.yml
        target: /etc/gitlab-ci-pipelines-exporter.yml
    networks:
      - prom-stack

  snmp:
    image: prom/snmp-exporter
    container_name: snmp-exporter
    command:
      - '--config.file=/config/snmp-conf.yml'
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    ports:
      - 9116:9116
    volumes:
      - ./config/snmp-exporter/:/config
    networks:
      - prom-stack


volumes:
  prometheus_data:
  grafana_data:

networks:
  prom-stack:
