groups:
- name: common-rules
  rules:
    # Alert for any instance that is unreachable for >2 minutes.
  - alert: Service Down
    # Condition for alerting (if up != 1)
    expr: up ==0 and up{job!="kube-proxy"} and up{namespace!="kube-system"}
    for: 1m
    # Labels - additional labels to be attached to the alert
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"      
    # Annotation - additional informational labels to store more information
    annotations:
      title: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} down, 1m \n Tag {{ $labels.tag }}"

  - alert: Critical CPU Load
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has Critical CPU load for more than 2 minutes. Tag {{ $labels.tag }}'
      summary: Instance {{ $labels.instance }} - Critical CPU load
    expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{job="node-exporter", mode="idle"}[1m])) * 100) > 80)
    for: 2m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"

  - alert: Critical RAM Usage
    annotations:
      description: '{{ $labels.instance }} has Critical Memory Usage more than 5 minutes. Tag {{ $labels.tag }}'
      summary: Instance {{ $labels.instance }} has Critical Memory Usage
    expr: (1 - ((node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes)) * 100 > 80
    for: 5m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"

  - alert: Critical Disk Space
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has less than 10% space remaining. Tag {{ $labels.tag }}'
      summary: Instance {{ $labels.instance }} - Critical disk space usage
    expr: node_filesystem_free_bytes{job="node-exporter", filesystem!~"^/run(/|$)"} / node_filesystem_size_bytes{job="node-exporter"} < 0.1
    for: 4m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"

  - alert: Reboot Required
    annotations:
      description: '{{ $labels.instance }} requires a reboot. Tag {{ $labels.tag }}'
      summary: Instance {{ $labels.instance }} - reboot required
    expr: node_reboot_required > 0
    labels:
      severity: warning
      tag: "{{ $labels.tag }}"





