########################
#### Site-memcached ####
########################
groups:
- name: memcached-rules
  rules:
  - alert: Memcached Down
    annotations:
      description: 'No idle memcached proc on {{ $labels.instance}} more than 2 minutes Tag {{ $labels.tag }}.'
      summary: No idle memcached proc on {{ $labels.instance}}
    expr: memcached_up{env="prod", tag="RV-SITE_memcached"} == 0
    for: 2m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"     

  - alert: Memcached Miss ratio more than 50%
    annotations:
      description: 'Miss ratio on {{ $labels.instance }} more than 50%. Tag {{ $labels.tag }}.'
      summary: 'Miss ratio on {{ $labels.instance }} more than 50%. Tag {{ $labels.tag }}.'
    expr: sum (memcached_commands_total{tag="RV-SITE_memcached", status="miss", command="get"}) / sum (memcached_commands_total{tag="RV-SITE_memcached", command="get"}) * 100 > 50
    for: 2m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"
