####################
#### Site-nginx ####
####################
groups:
- name: nginx-rules
  rules:
  - alert: Nginx Zero Connection
    annotations:
      description: '{{ $labels.condition }} active connection on {{ $labels.instance }}. Tag {{ $labels.tag }}'
      summary: '{{ $labels.condition }} active connection on {{ $labels.instance }}'
    expr: nginx_connections_active {env="prod", tag="RV-SITE_front"} == 0
    for: 2m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"

  - alert: Nginx Active Connections IS OVER 5000
    annotations:
      description: '{{ $labels.condition }} active connection on {{ $labels.instance }} Tag {{ $labels.tag }}'
      summary: '{{ $labels.condition }} active connection is {{ $value }} its less or more then range 100-6500 {{ $labels.instance }}'
    expr: nginx_connections_active {env="prod", tag="RV-SITE_front"} >= 5000
    for: 1m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"
      
  - alert: Nginx Down
    annotations:
      description: '{{ $labels.condition }} Nginx is Down on {{ $labels.instance}}. Tag {{ $labels.tag }}'
      summary: '{{ $labels.condition }} Nginx is Down on {{ $labels.instance }}'
    expr: nginx_up {env="prod", tag="RV-SITE_front"} == 0
    for: 2m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"
