##################
#### Site-sql ####
##################
groups:
- name: sql-rules
  rules:
  - alert: Mysql Down
    annotations:
      description: 'MySQL server down on {{ $labels.instance }}. Tag {{ $labels.tag }}'
      summary: MySQL server down on {{ $labels.instance }}
    expr: mysql_up {env="prod", tag="RV-SITE_db"} == 0
    for: 2m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"

  - alert: Mysql Slave IO
    annotations:
      description: 'MySQL Slave IO stop on {{ $labels.instance }}. Tag {{ $labels.tag }}'
      summary: MySQL Slave IO stop on {{ $labels.instance }}
    expr: mysql_slave_status_slave_io_running {env="prod", tag="RV-SITE_db"} == 0
    for: 2m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"

  - alert: Mysql Slave Sql
    annotations:
      description: 'MySQL Slave SQL stop on {{ $labels.instance }}. Tag {{ $labels.tag }}'
      summary: MySQL Slave SQL stop on {{ $labels.instance }}
    expr: mysql_slave_status_slave_sql_running {env="prod", tag="RV-SITE_db"} == 0
    for: 2m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"

  - alert: Mysql Slave Seconds Behind Master
    annotations:
      description: 'MySQL Slave {{ $labels.instance }} behind master in {{ $value }} Tag {{ $labels.tag }}'
        seconds.
      summary: MySQL Slave {{ $labels.instance }} behind master in {{ $value }}s
    expr: mysql_slave_status_seconds_behind_master {env="prod", tag="RV-SITE_db"} > 5
    for: 2m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"

  - alert: Mysql Low Connections
    annotations:
      description: 'Low MySQL connections on {{ $labels.instance }} is {{ $value }} connections. Tag {{ $labels.tag }}'
      summary: Low MySQL connections on {{ $labels.instance }} is {{ $value }} connections
    expr: rate(mysql_global_status_connections{env="prod", tag="RV-SITE_db"}[5m]) < 1 and hour() >= 3 <= 6 
    for: 2m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"

  - alert: Mysql Max Connections
    annotations:
      description: 'Max MySQL connections on {{ $labels.instance }} is {{ $value }} connections. Tag {{ $labels.tag }}'
      summary: Max MySQL connections on {{ $labels.instance }} is {{ $value }} connections
    expr: rate(mysql_global_status_connections{env="prod", tag="RV-SITE_db"}[5m]) > ( mysql_global_variables_max_connections{env="prod", tag="RV-SITE_db"} - 100) 
    for: 2m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"  
