global:
  resolve_timeout: 3m

templates:
#- '/etc/alertmanager/templates/*.tmpl'

route:
# ROCKET CHAT
  group_interval: 5m
  receiver: rocketchat
  repeat_interval: 30m

receivers:
# ROCKET CHAT
- name: rocketchat
  webhook_configs:
  - send_resolved: true
    url: https://chat.company.ru/hooks/BgbEC65Eqweqwe/BqweqweC

