version: '3.8'

networks:
  ${stack}-net:
    driver: bridge

volumes:
  ${stack}-database-data:
    external: true
  ${stack}-php-fpm71-dev-data:
    external: true
  ${stack}-phpsocket:

services:
  ${stack}-nginx:
    container_name: ${stack}-nginx
    image: docker.io/nginx:stable-alpine
    ports:
      - "${${stack}_EXT_IP}:80:80"
      - "${${stack}_EXT_IP}:443:443"
    depends_on:
      - ${stack}-php
    volumes:
      - ./volumes/nginx/conf.d/:/etc/nginx/conf.d
      - ./volumes/nginx/common/:/etc/nginx/common:ro
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/rv-ssl/:/etc/ssl/rv-ssl/:ro
      - ${stack}-php-fpm71-dev-data:/home/deploy:rw
      - ${stack}-phpsocket:/var/run
    networks:
      - ${stack}-net
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
    logging:
      options:
        tag: demodev.${stack}.nginx

  ${stack}-php:
    container_name: ${stack}-php
    image: dockerregistry.rendez-vous.ru/devops/rv-site/docker/php-backend-dev_alp:master
    environment:
      TZ: Europe/Moscow
      create_user: ${stack}
      create_passwd: SRZf8KEPbOrOiTA1
      XDEBUG_CONFIG: "client_host=${${stack}_ip} client_port=9001 start_with_request=yes log=/tmp/xdebug.log"
      XDEBUG_MODE: debug
      HOST_RESOLVER_DEFAULT_DOMAIN: ${HOST_RESOLVER_DEFAULT_DOMAIN}
      SENTRY_ENVIRONMENT: ${HOST_RESOLVER_DEFAULT_DOMAIN}
      PHP_PM_MODE: $PHP_PM_MODE
      PHP_MAX_CHILDREN: $PHP_MAX_CHILDREN
      PHP_START_SERVERS: $PHP_START_SERVERS
      PHP_MIN_SPARE_SERVERS: $PHP_MIN_SPARE_SERVERS
      PHP_MAX_SPARE_SERVERS: $PHP_MAX_SPARE_SERVERS
    volumes:
      - ${stack}-php-fpm71-dev-data:/home/deploy/
      - ${stack}-phpsocket:/var/run
    links:
      - "${stack}-database:site-db-master.rendez-vous.ru"
      - "${stack}-database:site-db-slave.rendez-vous.ru"
      - "${stack}-memcached-s:site-memcached.rendez-vous.ru"
      - "${stack}-memcached-s:site-memcached-s.rendez-vous.ru"
      - "${stack}-memcached-c:site-memcached-c.rendez-vous.ru"
    restart: unless-stopped
    networks:
      - ${stack}-net
    ports:
      - "${${stack}_EXT_IP}:22:22"
    cap_add:
     - SYS_PTRACE
    extra_hosts:
    - "host.docker.internal:host-gateway" 
    logging:
      options:
        tag: demodev.${stack}.php

  ${stack}-database:
    container_name: ${stack}-database
    image: percona:8.0.20-11
    environment:
      MYSQL_ROOT_PASSWORD: rS4EKcUU50uXRQYe
      MYSQL_DATABASE: rendez_vous
      MYSQL_USER: artektiv
      MYSQL_PASSWORD: O7UrtTt8HVT1W7ZxJmIwyB
      TZ: Europe/Moscow
    command: >
      --default-authentication-plugin=mysql_native_password
      --max-allowed-packet=1024M
      --innodb_log_file_size=1G
      --innodb-buffer-pool-size=6G
      --sql-mode="NO_ENGINE_SUBSTITUTION"
      --sort_buffer_size=4M
      --collation-server=utf8mb4_unicode_ci
      --character-set-server=utf8mb4
      --innodb_flush_log_at_trx_commit=0
      --bind-address=0.0.0.0
#--collation-server=utf8_unicode_ci --character-set-server=utf8
    volumes:
      - ${stack}-database-data:/var/lib/mysql
      - ./volumes/mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:ro
      - ./mysql.cnf:/etc/my.cnf.d/mysql.cnf
    restart: unless-stopped
    networks:
      - ${stack}-net
    ports:
      - "${${stack}_EXT_IP}:3306:3306"
    logging:
      options:
        tag: demodev.${stack}.db
#    security_opt:
#      - seccomp:unconfined

  ${stack}-memcached-s:
    container_name: ${stack}-memcached-s
    image: memcached:alpine
    command: memcached -m 64 -v
    restart: unless-stopped
    networks:
      - ${stack}-net
    logging:
      options:
        tag: demodev.${stack}.memcached-s

  ${stack}-memcached-c:
    container_name: ${stack}-memcached-c
    image: memcached:alpine
    command: memcached -p 11212 -m 64 -v
    expose:
      - "11212"
    restart: unless-stopped
    networks:
      - ${stack}-net
    logging:
      options:
        tag: demodev.${stack}.memcached-c
