[[servers]]
host = "company.ru"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = false
bind_dn = "CN=ldap_user_name,OU=Служебные учетные записи,OU=RU_Moscow,OU=.RV Users,OU=..company,DC=company,DC=ru"
bind_password = 'ldap_user_password'
search_filter = "(sAMAccountName=%s)"
search_base_dns = ["dc=company,dc=ru"]
[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "mail"

# Map ldap groups to grafana org roles
[[servers.group_mappings]]
group_dn = "CN=Grafana_Admin,OU=..Группы доступа,OU=..company,DC=company,DC=ru"
org_role = "Admin"

[[servers.group_mappings]]
group_dn = "cn=users,dc=grafana,dc=org"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"
