modules:
  main:  # The module name. You can have as many modules as you want.
    walk:       # List of OIDs to walk. Can also be SNMP object names or specific instances.
    - rPDU2DeviceStatusPower
    version: 2  # SNMP version to use. Defaults to 2.
                # 1 will use GETNEXT, 2 and 3 use GETBULK.
    max_repetitions: 25  # How many objects to request with GET/GETBULK, defaults to 25.
                         # May need to be reduced for buggy devices.
    retries: 3   # How many times to retry a failed request, defaults to 3.
    timeout: 5s  # Timeout for each individual SNMP request, defaults to 5s.
    auth:
      # Community string is used with SNMP v1 and v2. Defaults to "public".
      #community: public
      community: I9Ukl50E
      # v3 has different and more complex settings.
      # Which are required depends on the security_level.
      # The equivalent options on NetSNMP commands like snmpbulkwalk
      # and snmpget are also listed. See snmpcmd(1).
      #username: xxx # Required, no default. -u option to NetSNMP.
      #security_level: xxx # Defaults to noAuthNoPriv. -l option to NetSNMP.
      #                              # Can be noAuthNoPriv, authNoPriv or authPriv.
      #password: xxx  # Has no default. Also known as authKey, -A option to NetSNMP.
      #                # Required if security_level is authNoPriv or authPriv.
      #auth_protocol: xxx # MD5, SHA, SHA224, SHA256, SHA384, or SHA512. Defaults to MD5. -a option to NetSNMP.
      #                    # Used if security_level is authNoPriv or authPriv.
      #priv_protocol: xxx # DES, AES, AES192, or AES256. Defaults to DES. -x option to NetSNMP.
      #                    # Used if security_level is authPriv.
      #priv_password: xxx # Has no default. Also known as privKey, -X option to NetSNMP.
      #                         # Required if security_level is authPriv.
      #context_name: xxx # Has no default. -n option to NetSNMP.
      #                      # Required if context is configured on the device.

