alertmanager:
  alertmanagerSpec:
    tolerations:
    - key: "node-role/clickhouse"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role/rvsite"
      operator: "Exists"
      effect: "NoSchedule"

grafana:
  enabled: true
  adminPassword: prom-operator
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: {}
    labels: {}
    hosts:
      - k8s-grafana.rendez-vous.ru
    paths:
    - /
    pathType: ImplementationSpecific

## Manages Prometheus and Alertmanager components
##
prometheusOperator:
  enabled: true
  tolerations:
    - key: "node-role/clickhouse"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role/rvsite"

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: {}
    labels: {}
    hosts:
      - k8sprom.rendez-vous.ru
    paths:
    - /
    pathType: ImplementationSpecific
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    tolerations:
    - key: "node-role/clickhouse"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role/rvsite"
      operator: "Exists"
      effect: "NoSchedule"
