##################
#### Site-mysql ####
##################
groups:
- name: mysql-rules
  rules:
  - alert: Mysql Down
    annotations:
      description: 'MySQL server down on {{ $labels.instance }}.'
      summary: MySQL server down on {{ $labels.instance }}
    #expr: mysql_up {env="prod", tag="RV-SITE_db"} == 0
    expr: mysql_up == 0
    for: 2m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"

  - alert: Mysql Slave IO stop
    annotations:
      description: 'MySQL Slave IO stop on {{ $labels.instance }}.'
      summary: MySQL Slave IO stop on {{ $labels.instance }}
    #expr: mysql_slave_status_slave_io_running {env="prod", tag="RV-SITE_db"} == 0
    expr: mysql_slave_status_slave_io_running == 0
    for: 2m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"

  - alert: Mysql Slave Sql stop
    annotations:
      description: 'MySQL Slave SQL stop on {{ $labels.instance }}.'
      summary: MySQL Slave SQL stop on {{ $labels.instance }}
    expr: mysql_slave_status_slave_sql_running {env="prod", tag="RV-SITE_db"} == 0
    for: 2m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"

  - alert: Mysql Slave Seconds Behind Master
    annotations:
      description: 'MySQL Slave {{ $labels.instance }} behind master in {{ $value }} seconds.'
      summary: MySQL Slave {{ $labels.instance }} behind master in {{ $value }}s
    #expr: mysql_slave_status_seconds_behind_master {env="prod", tag="RV-SITE_db"} > 5
    expr: mysql_slave_status_seconds_behind_master >= 5
    for: 2m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"

  - alert: MysqlSlaveIoThreadNotRunning
    expr: mysql_slave_status_master_server_id > 0 and ON (instance) mysql_slave_status_slave_io_running == 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: MySQL Slave IO thread not running (instance {{ $labels.instance }})
      description: "MySQL Slave IO thread not running on {{ $labels.instance }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: MysqlSlaveSqlThreadNotRunning
    expr: mysql_slave_status_master_server_id > 0 and ON (instance) mysql_slave_status_slave_sql_running == 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: MySQL Slave SQL thread not running (instance {{ $labels.instance }})
      description: "MySQL Slave SQL thread not running on {{ $labels.instance }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: Mysql Low Connections
    annotations:
      description: 'Low MySQL connections on {{ $labels.instance }} is {{ $value }} connections.'
      summary: Low MySQL connections on {{ $labels.instance }} is {{ $value }} connections
    expr: rate(mysql_global_status_connections{env="prod", tag="RV-SITE_db"}[5m]) < 1 and hour() >= 3 <= 6 
    for: 2m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"

  - alert: MysqlRestarted
    expr: mysql_global_status_uptime < 60
    for: 0m
    labels:
      severity: info
    annotations:
      summary: MySQL restarted (instance {{ $labels.instance }})
      description: "MySQL has just been restarted, less than one minute ago on {{ $labels.instance }}.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      
  - alert: MysqlInnodbLogWaits
    expr: rate(mysql_global_status_innodb_log_waits[15m]) > 10
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: MySQL InnoDB log waits (instance {{ $labels.instance }})
      description: "MySQL innodb log writes stalling\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: MysqlSlowQueries
    expr: increase(mysql_global_status_slow_queries[1m]) > 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: MySQL slow queries (instance {{ $labels.instance }})
      description: "MySQL server mysql has some new slow query.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


  - alert: MysqlTooManyConnections(>80%)
    expr: avg by (instance) (rate(mysql_global_status_threads_connected[1m])) / avg by (instance) (mysql_global_variables_max_connections) * 100 > 80
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: MySQL too many connections (> 80%) (instance {{ $labels.instance }})
      description: "More than 80% of MySQL connections are in use on {{ $labels.instance }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: MysqlHighThreadsRunning
    expr: avg by (instance) (rate(mysql_global_status_threads_running[1m])) / avg by (instance) (mysql_global_variables_max_connections) * 100 > 60
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: MySQL high threads running (instance {{ $labels.instance }})
      description: "More than 60% of MySQL connections are in running state on {{ $labels.instance }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


  - alert: Mysql Max Connections
    annotations:
      description: 'Max MySQL connections on {{ $labels.instance }} is {{ $value }} connections.'
      summary: Max MySQL connections on {{ $labels.instance }} is {{ $value }} connections
    expr: rate(mysql_global_status_connections{env="prod", tag="RV-SITE_db"}[5m]) > ( mysql_global_variables_max_connections{env="prod", tag="RV-SITE_db"} - 100) 
    for: 2m
    labels:
      severity: critical
      tag: "{{ $labels.tag }}"  
