apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-exporter-http
  namespace: monitoring
  labels:
    app: 'blackbox-exporter'
    release: prometheus
spec:
  jobName: http-get
  interval: 1m
  scrapeTimeout: 5s
  module: http_2xx
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring:9115
    scheme: http
    path: /probe
  targets:
    staticConfig:
      static:
      - https://confluence.company.com
